"""add last_login_at to user

Revision ID: 03ecb262ee25
Revises: f014_cleanup_run_last_login
Create Date: 2026-02-07 19:03:27.370665

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '03ecb262ee25'
down_revision = 'f014_cleanup_run_last_login'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistant_daily_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assistant_daily_usage_usage_date'), ['usage_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_assistant_daily_usage_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('assistant_daily_usage_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('assistant_reminder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assistant_reminder_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('assistant_reminder_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('assistant_watchlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assistant_watchlist_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('assistant_watchlist_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('buyer_request_alert', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_buyer_request_alert_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('buyer_request_alert_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('cleanup_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cleanup_run_ran_by_user'))
        batch_op.create_index(batch_op.f('ix_cleanup_run_ran_by_user_id'), ['ran_by_user_id'], unique=False)

    with op.batch_alter_table('marketplace_alert', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketplace_alert_user_id'), ['user_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('marketplace_alert_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)

    with op.batch_alter_table('marketplace_alert', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('marketplace_alert_user_id_fkey'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_marketplace_alert_user_id'))

    with op.batch_alter_table('cleanup_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cleanup_run_ran_by_user_id'))
        batch_op.create_index(batch_op.f('ix_cleanup_run_ran_by_user'), ['ran_by_user_id'], unique=False)

    with op.batch_alter_table('buyer_request_alert', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('buyer_request_alert_user_id_fkey'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_buyer_request_alert_user_id'))

    with op.batch_alter_table('assistant_watchlist', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('assistant_watchlist_user_id_fkey'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_assistant_watchlist_user_id'))

    with op.batch_alter_table('assistant_reminder', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('assistant_reminder_user_id_fkey'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_assistant_reminder_user_id'))

    with op.batch_alter_table('assistant_daily_usage', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('assistant_daily_usage_user_id_fkey'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_assistant_daily_usage_user_id'))
        batch_op.drop_index(batch_op.f('ix_assistant_daily_usage_usage_date'))

    # ### end Alembic commands ###
