"""add user_device table

Revision ID: 0a1cf6d00de4
Revises: 23a120abb949
Create Date: 2026-01-25 17:10:26.216529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a1cf6d00de4'
down_revision = '23a120abb949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_id', name='uq_user_device')
    )
    with op.batch_alter_table('user_device', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_device_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_device_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_device_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_device_device_id'))

    op.drop_table('user_device')
    # ### end Alembic commands ###
