"""add device_trial counter

Revision ID: 0dfdcc12c488
Revises: 0a1cf6d00de4
Create Date: 2026-01-25 23:02:46.160980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dfdcc12c488'
down_revision = '0a1cf6d00de4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_trial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('trial_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_trial', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_trial_device_id'), ['device_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_trial', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_trial_device_id'))

    op.drop_table('device_trial')
    # ### end Alembic commands ###
