"""add user_profile relationship

Revision ID: 23a120abb949
Revises: c5b6aa3fcabe
Create Date: 2026-01-25 16:14:07.638779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a120abb949'
down_revision = 'c5b6aa3fcabe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=120), nullable=False),
    sa.Column('agent_signature_dataurl', sa.Text(), nullable=False),
    sa.Column('agency_name', sa.String(length=160), nullable=False),
    sa.Column('agency_hq_address', sa.String(length=255), nullable=False),
    sa.Column('agency_orc_number', sa.String(length=80), nullable=False),
    sa.Column('agency_cui', sa.String(length=80), nullable=False),
    sa.Column('agency_iban', sa.String(length=80), nullable=False),
    sa.Column('agency_bank', sa.String(length=120), nullable=False),
    sa.Column('agency_administrator', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profile')
    # ### end Alembic commands ###
