"""add trial_ends_at to user

Revision ID: 23d491d61f3f
Revises: 94c56e0df8ab
Create Date: 2026-01-29 11:42:10.306495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23d491d61f3f'
down_revision = '94c56e0df8ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chirie_remote_signing', schema=None) as batch_op:
        batch_op.drop_column('viz_cnp')

    with op.batch_alter_table('vanzare_remote_signing', schema=None) as batch_op:
        batch_op.drop_column('viz_cnp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vanzare_remote_signing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('viz_cnp', sa.VARCHAR(length=32), autoincrement=False, nullable=True))

    with op.batch_alter_table('chirie_remote_signing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('viz_cnp', sa.VARCHAR(length=32), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
