"""add trial paid fields

Revision ID: c5b6aa3fcabe
Revises: a7e28fc581eb
Create Date: 2026-01-25 13:01:07.290184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c5b6aa3fcabe'
down_revision = 'a7e28fc581eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('paid_ends_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(
            sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true'))
        )
        batch_op.alter_column('is_active', server_default=None)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('is_active')
        batch_op.drop_column('paid_ends_at')
        batch_op.drop_column('trial_ends_at')

    # ### end Alembic commands ###
