"""add chirie_remote_signing

Revision ID: ed72721c5dac
Revises: 0dfdcc12c488
Create Date: 2026-01-28 18:43:45.169838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed72721c5dac'
down_revision = '0dfdcc12c488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chirie_remote_signing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('public_token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_vizionarii', sa.String(length=20), nullable=False),
    sa.Column('ora_vizionarii', sa.String(length=10), nullable=False),
    sa.Column('tip_imobil', sa.String(length=120), nullable=False),
    sa.Column('adresa_full', sa.String(length=255), nullable=False),
    sa.Column('adresa_public', sa.String(length=255), nullable=False),
    sa.Column('comision_procent', sa.String(length=50), nullable=False),
    sa.Column('signature_agent_dataurl', sa.Text(), nullable=True),
    sa.Column('signature_visitor_dataurl', sa.Text(), nullable=True),
    sa.Column('viz_nume', sa.String(length=160), nullable=True),
    sa.Column('viz_telefon', sa.String(length=50), nullable=True),
    sa.Column('viz_email', sa.String(length=160), nullable=True),
    sa.Column('pdf_doc_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chirie_remote_signing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chirie_remote_signing_public_token'), ['public_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_chirie_remote_signing_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_chirie_remote_signing_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_chirie_remote_user_status', ['user_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chirie_remote_signing', schema=None) as batch_op:
        batch_op.drop_index('ix_chirie_remote_user_status')
        batch_op.drop_index(batch_op.f('ix_chirie_remote_signing_user_id'))
        batch_op.drop_index(batch_op.f('ix_chirie_remote_signing_status'))
        batch_op.drop_index(batch_op.f('ix_chirie_remote_signing_public_token'))

    op.drop_table('chirie_remote_signing')
    # ### end Alembic commands ###
